#### Instruction (Read this)
- Use this template to develop your project. Do not change the steps. 
- For each step, you may add additional cells if needed.
- But remove <b>unnecessary</b> cells to ensure the notebook is readable.
- Marks will be <b>deducted</b> if the notebook is cluttered or difficult to follow due to excess or irrelevant content.
- <b>Briefly</b> describe the steps in the "Description:" field.
- <b>Do not</b> submit the dataset. 
- The submitted jupyter notebook will be executed using the uploaded dataset in eLearn.

#### Group Information

Group No: Cancer2

- Member 1:MUHAMMAD DANISH AIMAN BIN MUHAMMAD NAZIR
- Member 2:MUHAMMAD AMMAR BIN ADNAN
- Member 3:ARDY QAWI BIN HASHIM
- Member 4:MAHDIL ASHRONIE BIN MUHAMAD MURTADZA


#### Import libraries

In [33]:
%config Completer.use_jedi=False # comment if not needed
import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
warnings.filterwarnings('ignore')

#### Load the dataset

In [34]:
df = pd.read_csv('risk_factors.csv', na_values='?')

In [35]:
df.shape
df.sample(10)

Age  Number of sexual partners  First sexual intercourse  \
490   26                        2.0                      16.0   
144   29                        2.0                      17.0   
644   40                        3.0                      23.0   
592   21                        1.0                      18.0   
220   26                        1.0                      18.0   
346   20                        3.0                      17.0   
198   30                        1.0                      23.0   
376   35                        2.0                      17.0   
544   42                        3.0                      18.0   
249   25                        2.0                      18.0   

     Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
490                 3.0     1.0             1.0                  1.0   
144                 2.0     0.0             0.0                  0.0   
644                 2.0     0.0             0.0                  0.0   
592                 1.0     0.0             0.0                  0.0   
220                 2.0     0.0             0.0                  0.0   
346                 2.0     0.0             0.0                  0.0   
198                 1.0     0.0             0.0                  0.0   
376                 3.0     0.0             0.0                  0.0   
544                 4.0     0.0             0.0                  0.0   
249                 3.0     0.0             0.0                  0.0   

     Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD  ...  \
490                      1.0                             2.00  0.0  ...   
144                      1.0                             9.00  0.0  ...   
644                      0.0                             0.00  0.0  ...   
592                      1.0                             2.00  0.0  ...   
220                      0.0                             0.00  0.0  ...   
346                      1.0                             0.25  0.0  ...   
198                      1.0                             0.08  0.0  ...   
376                      1.0                             1.00  0.0  ...   
544                      1.0                             1.00  0.0  ...   
249                      1.0                             5.00  0.0  ...   

     STDs:HPV  STDs: Number of diagnosis  Dx:Cancer  Dx:CIN  Dx:HPV  Dx  \
490       0.0                          0          0       0       0   0   
144       0.0                          0          0       0       0   0   
644       0.0                          1          0       0       0   0   
592       0.0                          0          0       0       0   0   
220       0.0                          0          0       0       0   0   
346       0.0                          0          0       0       0   0   
198       0.0                          0          0       0       0   0   
376       0.0                          0          0       0       0   0   
544       0.0                          1          0       0       0   0   
249       0.0                          0          0       0       0   0   

     Hinselmann  Schiller  Citology  Biopsy  
490           0         0         0       0  
144           0         0         0       0  
644           0         0         0       0  
592           0         0         0       0  
220           0         0         0       0  
346           0         0         1       1  
198           0         0         0       0  
376           1         1         0       1  
544           0         0         0       0  
249           0         0         0       0  

[10 rows x 34 columns]

#### Split the dataset
Split the dataset into training, validation and test sets.

In [36]:
y = df[['Hinselmann', 'Schiller', 'Citology', 'Biopsy']]
X = df.drop(['Hinselmann', 'Schiller', 'Citology', 'Biopsy'], axis=1)
scaler = StandardScaler()
X_transform = scaler.fit_transform(X)


In [37]:
seed_num = 10
X_train, X_test, y_train, y_test = train_test_split(X_transform, y, test_size=0.3, random_state=seed_num) # random_state is set to a value for reproducible␣output.
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=seed_num)
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(373, 30)
(94, 30)
(201, 30)


#### Data preprocessing
Perform data preprocessing such as normalization, standardization, label encoding etc.
______________________________________________________________________________________
Description:

##### Handling Boolean Values

In [38]:
# Convert boolean-like columns to proper boolean data types
boolean_cols = [
    'Smokes', 'Smokes (years)', 'Smokes (packs/year)', 'Hormonal Contraceptives', 'IUD',
    'STDs', 'STDs:condylomatosis', 'STDs:cervical condylomatosis', 'STDs:vaginal condylomatosis',
    'STDs:vulvo-perineal condylomatosis', 'STDs:syphilis', 'STDs:pelvic inflammatory disease',
    'STDs:genital herpes', 'STDs:molluscum contagiosum', 'STDs:AIDS', 'STDs:HIV', 'STDs:Hepatitis B',
    'STDs:HPV', 'Dx:Cancer', 'Dx:CIN', 'Dx:HPV', 'Dx', 'Hinselmann', 'Schiller', 'Citology', 'Biopsy'
]

# Convert boolean-like columns to numeric
df[boolean_cols] = df[boolean_cols].apply(pd.to_numeric, errors='coerce')

# Replace values greater than 0 with 1, leave missing values untouched
df[boolean_cols] = df[boolean_cols].applymap(lambda x: 1 if x > 0 else x)


##### Check for the sum of missing values

In [39]:
print(df.isnull().sum())

Age                                   0
Number of sexual partners             0
First sexual intercourse              0
Num of pregnancies                    0
Smokes                                0
Smokes (years)                        0
Smokes (packs/year)                   0
Hormonal Contraceptives               0
Hormonal Contraceptives (years)       0
IUD                                   0
IUD (years)                           0
STDs                                  0
STDs (number)                         0
STDs:condylomatosis                   0
STDs:cervical condylomatosis          0
STDs:vaginal condylomatosis           0
STDs:vulvo-perineal condylomatosis    0
STDs:syphilis                         0
STDs:pelvic inflammatory disease      0
STDs:genital herpes                   0
STDs:molluscum contagiosum            0
STDs:AIDS                             0
STDs:HIV                              0
STDs:Hepatitis B                      0
STDs:HPV                              0


##### Dropping Columns with too high missing values

In [41]:
# Set the threshold for dropping columns
threshold = 0.5  #keep columns with at least 50% non-null values

# Calculate the minimum number of non-null values required for each column to be retained
min_non_null_values = len(df) * threshold

# Drop columns with too many missing values
df = df.dropna(axis=1, thresh=min_non_null_values)

# Print the remaining missing values count after dropping columns
print(df.isnull().sum())

df.shape


Age                                   0
Number of sexual partners             0
First sexual intercourse              0
Num of pregnancies                    0
Smokes                                0
Smokes (years)                        0
Smokes (packs/year)                   0
Hormonal Contraceptives               0
Hormonal Contraceptives (years)       0
IUD                                   0
IUD (years)                           0
STDs                                  0
STDs (number)                         0
STDs:condylomatosis                   0
STDs:cervical condylomatosis          0
STDs:vaginal condylomatosis           0
STDs:vulvo-perineal condylomatosis    0
STDs:syphilis                         0
STDs:pelvic inflammatory disease      0
STDs:genital herpes                   0
STDs:molluscum contagiosum            0
STDs:AIDS                             0
STDs:HIV                              0
STDs:Hepatitis B                      0
STDs:HPV                              0


(668, 34)

##### Dropping Rows with missing values

In [42]:
# Drop rows with missing values
df = df.dropna()

# Print the remaining missing values count after dropping rows
print(df.isnull().sum())

# Print the shape of the cleaned dataset
df.shape

#export cleaned data
df.to_csv('risk_factors_clean.csv', index=False)

Age                                   0
Number of sexual partners             0
First sexual intercourse              0
Num of pregnancies                    0
Smokes                                0
Smokes (years)                        0
Smokes (packs/year)                   0
Hormonal Contraceptives               0
Hormonal Contraceptives (years)       0
IUD                                   0
IUD (years)                           0
STDs                                  0
STDs (number)                         0
STDs:condylomatosis                   0
STDs:cervical condylomatosis          0
STDs:vaginal condylomatosis           0
STDs:vulvo-perineal condylomatosis    0
STDs:syphilis                         0
STDs:pelvic inflammatory disease      0
STDs:genital herpes                   0
STDs:molluscum contagiosum            0
STDs:AIDS                             0
STDs:HIV                              0
STDs:Hepatitis B                      0
STDs:HPV                              0


#### Feature Selection
Perform feature selection to select the relevant features.
______________________________________________________________________________________
Feature Selection Using Random Forest

Step 1: Loading dataset

Step 2: Train Test Split

Step 3: Import Random Forest Classifier module.

Step 4: Training of Model

In [43]:
df = pd.read_csv('risk_factors_clean.csv', na_values='?')

In [44]:
y = df[['Hinselmann', 'Schiller', 'Citology', 'Biopsy']]
X = df.drop(['Hinselmann', 'Schiller', 'Citology', 'Biopsy'], axis=1)
scaler = StandardScaler()
X_transform = scaler.fit_transform(X)

In [45]:
seed_num = 10
X_train, X_test, y_train, y_test = train_test_split(X_transform, y, test_size=0.3, random_state=seed_num) # random_state is set to a value for reproducible␣output.

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
# creating a RF classifier
clf = RandomForestClassifier(n_estimators = 100)  
 
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)
 
# performing predictions on the test dataset
y_pred = clf.predict(X_test)
 
# metrics are used to find accuracy or error
from sklearn import metrics  
print()
 
# using metrics module for accuracy calculation
print("ACCURACY OF THE MODEL:", metrics.accuracy_score(y_test, y_pred))


ACCURACY OF THE MODEL: 0.8606965174129353


In [48]:
feature_imp = pd.Series(clf.feature_importances_, index = X.columns).sort_values(ascending = False)
feature_imp ##print the features significant in ascending order

Age                                   0.220102
First sexual intercourse              0.153943
Hormonal Contraceptives (years)       0.151702
Number of sexual partners             0.109701
Num of pregnancies                    0.098737
IUD (years)                           0.037467
Dx:HPV                                0.030936
Dx:Cancer                             0.023941
Hormonal Contraceptives               0.023679
STDs:HIV                              0.020636
STDs (number)                         0.019537
IUD                                   0.019146
Smokes (packs/year)                   0.014988
Dx                                    0.013433
Smokes (years)                        0.012917
STDs: Number of diagnosis             0.012251
Smokes                                0.011495
STDs:vulvo-perineal condylomatosis    0.006386
STDs                                  0.005342
STDs:condylomatosis                   0.004784
STDs:syphilis                         0.003029
Dx:CIN       

In [49]:
##Take 5 most important features
X = df[['Age','First sexual intercourse', 'Hormonal Contraceptives (years)', 'Number of sexual partners', 'Num of pregnancies']]

In [50]:
seed_num = 10
X_train, X_test, y_train, y_test = train_test_split(X_transform, y, test_size=0.3, random_state=seed_num) # random_state is set to a value for reproducible␣output.

In [51]:
# creating a RF classifier
clf = RandomForestClassifier(n_estimators = 100)  
 
# Training the model on the training dataset
# fit function is used to train the model using the training sets as parameters
clf.fit(X_train, y_train)
 
# performing predictions on the test dataset
y_pred = clf.predict(X_test)
 
# metrics are used to find accuracy or error
from sklearn import metrics  
print()
 
# using metrics module for accuracy calculation
print("ACCURACY OF THE MODEL:", metrics.accuracy_score(y_test, y_pred))


ACCURACY OF THE MODEL: 0.8656716417910447


_**As the result, the accuracy of the model when we take the 5 most significant features is exactly
the same as the accuracy of the model using all 30 features, indicating that the selected features effectively 
capture the essential information for making predictions.**_

#### Data modeling
Build the machine learning models. You must build atleast two (2) predictive models. One of the predictive models must be either Decision Tree or Support Vector Machine.
______________________________________________________________________________________
Description:

## Decision Tree

In [60]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

# Define the parameter grid including ccp_alpha for pruning
parameters = {
    'estimator__max_depth': [None, 10, 20, 30],
    'estimator__min_samples_split': [2, 5, 10],
    'estimator__min_samples_leaf': [1, 2, 4],
    'estimator__ccp_alpha': [0.0, 0.01, 0.05, 0.1]
}

clf = MultiOutputClassifier(DecisionTreeClassifier(random_state=seed_num))
gsc = GridSearchCV(clf, parameters, cv=3, scoring=['accuracy', 'precision_weighted', 'recall_weighted', 'f1_weighted'], n_jobs=3, refit='f1_weighted')
gsc.fit(X_train, y_train)
cv_results_dt = gsc.cv_results_

for mean_score, params in zip(cv_results_dt['mean_test_f1_weighted'], cv_results_dt['params']):
    print(f"Mean F1 score: {mean_score} with parameters: {params}")


Mean F1 score: 0.12725572770309615 with parameters: {'estimator__ccp_alpha': 0.0, 'estimator__max_depth': None, 'estimator__min_samples_leaf': 1, 'estimator__min_samples_split': 2}
Mean F1 score: 0.1375685560419454 with parameters: {'estimator__ccp_alpha': 0.0, 'estimator__max_depth': None, 'estimator__min_samples_leaf': 1, 'estimator__min_samples_split': 5}
Mean F1 score: 0.06822190155523489 with parameters: {'estimator__ccp_alpha': 0.0, 'estimator__max_depth': None, 'estimator__min_samples_leaf': 1, 'estimator__min_samples_split': 10}
Mean F1 score: 0.1432551575408718 with parameters: {'estimator__ccp_alpha': 0.0, 'estimator__max_depth': None, 'estimator__min_samples_leaf': 2, 'estimator__min_samples_split': 2}
Mean F1 score: 0.09562769505626646 with parameters: {'estimator__ccp_alpha': 0.0, 'estimator__max_depth': None, 'estimator__min_samples_leaf': 2, 'estimator__min_samples_split': 5}
Mean F1 score: 0.05291406124739458 with parameters: {'estimator__ccp_alpha': 0.0, 'estimator__ma

In [61]:
print(f"Best parameters found: {gsc.best_params_}")
print(f"Best F1 score: {gsc.best_score_}")

Best parameters found: {'estimator__ccp_alpha': 0.0, 'estimator__max_depth': 10, 'estimator__min_samples_leaf': 2, 'estimator__min_samples_split': 2}
Best F1 score: 0.15794553594553593


In [62]:
from sklearn.tree import DecisionTreeClassifier

# Obtain the best parameters from hyperparameter tuning
best_params = gsc.best_params_

# Create a decision tree classifier with the best parameters
best_dt_model = DecisionTreeClassifier(max_depth=best_params['estimator__max_depth'], 
                                       min_samples_split=best_params['estimator__min_samples_split'], 
                                       min_samples_leaf=best_params['estimator__min_samples_leaf'],
                                       ccp_alpha=best_params['estimator__ccp_alpha'])

# Fit the model to the training data
best_dt_model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=2)

In [63]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

best_model = gsc.best_estimator_
y_pred_test = best_model.predict(X_test)
y_pred_test_df = pd.DataFrame(y_pred_test, columns=y.columns)
test_metrics = {}

# Calculate metrics for each target
for target in y.columns:
    accuracy = accuracy_score(y_test[target], y_pred_test_df[target])
    recall = recall_score(y_test[target], y_pred_test_df[target], average='weighted')
    precision = precision_score(y_test[target], y_pred_test_df[target], average='weighted')
    f1 = f1_score(y_test[target], y_pred_test_df[target], average='weighted')
    cm = confusion_matrix(y_test[target], y_pred_test_df[target])
    
    test_metrics[target] = {
        'accuracy': accuracy,
        'recall': recall,
        'precision': precision,
        'f1': f1,
        'confusion_matrix': cm
    }

In [64]:
# Print the metrics for each target
for target, metrics in test_metrics.items():
    print(f"\nMetrics for Decision Tree Model predicting {target}:")
    print(f"Accuracy: {metrics['accuracy']}")
    print(f"Recall: {metrics['recall']}")
    print(f"Precision: {metrics['precision']}")
    print(f"F1-Score: {metrics['f1']}")
    print(f"Confusion Matrix:\n{metrics['confusion_matrix']}")


Metrics for Decision Tree Model predicting Hinselmann:
Accuracy: 0.9303482587064676
Recall: 0.9303482587064676
Precision: 0.9208062252838373
F1-Score: 0.9255526491255065
Confusion Matrix:
[[187   6]
 [  8   0]]

Metrics for Decision Tree Model predicting Schiller:
Accuracy: 0.8656716417910447
Recall: 0.8656716417910447
Precision: 0.8363539445628998
F1-Score: 0.8489922891087798
Confusion Matrix:
[[171   9]
 [ 18   3]]

Metrics for Decision Tree Model predicting Citology:
Accuracy: 0.945273631840796
Recall: 0.945273631840796
Precision: 0.9120228005700143
F1-Score: 0.9283505744932626
Confusion Matrix:
[[190   2]
 [  9   0]]

Metrics for Decision Tree Model predicting Biopsy:
Accuracy: 0.9054726368159204
Recall: 0.9054726368159204
Precision: 0.8713738997321087
F1-Score: 0.8863332381959718
Confusion Matrix:
[[181   5]
 [ 14   1]]


#### Regression problem Decision Tree

In [65]:
# Train Decision Tree Regressor with pruning
best_params_regressor = {'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 1, 'ccp_alpha': gsc.best_params_['estimator__ccp_alpha']}
dt_regressor = DecisionTreeRegressor(**best_params_regressor, random_state=seed_num)
dt_regressor.fit(X_train, y_train[target])

DecisionTreeRegressor(max_depth=10, random_state=10)

In [66]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Define the parameter grid for the Decision Tree Regressor
regressor_params = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'ccp_alpha': [0.0, 0.001, 0.01, 0.1] 
}

# Initialize dictionaries to store metrics for each target
dt_r2_scores = {}
dt_mse_scores = {}
dt_mae_scores = {}

# Evaluate Decision Tree Regressor for each target
for target in y.columns:
    # Perform GridSearchCV for each target
    dt_regressor = DecisionTreeRegressor(random_state=seed_num)
    gsc_reg = GridSearchCV(dt_regressor, regressor_params, cv=5, scoring='neg_mean_squared_error', n_jobs=3)
    gsc_reg.fit(X_train, y_train[target])
    
    best_regressor = gsc_reg.best_estimator_
    dt_predictions = best_regressor.predict(X_test)
    
    # Calculate metrics
    dt_r2_scores[target] = r2_score(y_test[target], dt_predictions)
    dt_mse_scores[target] = mean_squared_error(y_test[target], dt_predictions)
    dt_mae_scores[target] = mean_absolute_error(y_test[target], dt_predictions)
    
    print(f"\nBest parameters for Decision Tree Regressor predicting {target}: {gsc_reg.best_params_}")


Best parameters for Decision Tree Regressor predicting Hinselmann: {'ccp_alpha': 0.01, 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}

Best parameters for Decision Tree Regressor predicting Schiller: {'ccp_alpha': 0.01, 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}

Best parameters for Decision Tree Regressor predicting Citology: {'ccp_alpha': 0.01, 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}

Best parameters for Decision Tree Regressor predicting Biopsy: {'ccp_alpha': 0.01, 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}


In [67]:
# Print metrics for Decision Tree Regressor for each target
for target in y.columns:
    print(f"\nMetrics for Decision Tree Regressor predicting {target}:")
    print(f"R2 Score: {dt_r2_scores[target]}")
    print(f"Mean Squared Error: {dt_mse_scores[target]}")
    print(f"Mean Absolute Error: {dt_mae_scores[target]}")


Metrics for Decision Tree Regressor predicting Hinselmann:
R2 Score: -0.0013975494199180982
Mean Squared Error: 0.03827028579253863
Mean Absolute Error: 0.0831602160503691

Metrics for Decision Tree Regressor predicting Schiller:
R2 Score: -0.0022601628998561996
Mean Squared Error: 0.09377350599642229
Mean Absolute Error: 0.17562082521013775

Metrics for Decision Tree Regressor predicting Citology:
R2 Score: -0.00885726412152854
Mean Squared Error: 0.04315005451355167
Mean Absolute Error: 0.10326312761673433

Metrics for Decision Tree Regressor predicting Biopsy:
R2 Score: -0.001562324585153485
Mean Squared Error: 0.06916558712884777
Mean Absolute Error: 0.12927866023203044


## Support Vector Machine

In [68]:
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import GridSearchCV 
from sklearn.svm import SVC

parameters = {'estimator__kernel': ['linear', 'sigmoid'], 'estimator__C': [0.1, 0.5, 1, 5], 'estimator__coef0': [0, 2, 5]}
clf = MultiOutputClassifier(SVC())
gsc = GridSearchCV(clf, parameters, cv=3, scoring=['accuracy', 'precision', 'recall', 'f1'], n_jobs=3, refit='f1')
gsc.fit(X_train, y_train)
gsc.cv_results_


{'mean_fit_time': array([0.01811107, 0.01046594, 0.01182111, 0.01185544, 0.01000571,
        0.00955375, 0.00970785, 0.01077922, 0.01020718, 0.01064459,
        0.01178622, 0.01005967, 0.01045513, 0.01131217, 0.01066971,
        0.00932892, 0.01320132, 0.00896152, 0.01599781, 0.00967852,
        0.01700298, 0.01332283, 0.02243535, 0.01076722]),
 'std_fit_time': array([5.66859591e-04, 4.11846747e-04, 2.34240190e-03, 1.62522424e-03,
        7.15718464e-04, 2.83710318e-05, 1.28955398e-03, 5.53955032e-04,
        8.36017278e-04, 3.44014648e-04, 1.86005133e-03, 8.30273257e-04,
        1.05251566e-03, 1.81087955e-03, 1.17754765e-03, 4.74520553e-04,
        1.68662783e-03, 1.00101990e-04, 2.91539809e-03, 9.62859295e-04,
        3.19443901e-03, 9.29261199e-04, 6.94118580e-03, 8.99509054e-04]),
 'mean_score_time': array([0.03351506, 0.00633605, 0.00779692, 0.00761286, 0.00737604,
        0.00704058, 0.00700259, 0.00764124, 0.00757996, 0.00756335,
        0.00680168, 0.00666674, 0.00676521, 0.00

In [69]:
print(gsc.best_params_)
print(gsc.best_index_)

{'estimator__C': 0.1, 'estimator__coef0': 0, 'estimator__kernel': 'linear'}
0


**Build SVM model with the best parameters**

In [70]:
from sklearn.svm import SVC
C = 0.1
model_svc = SVC(kernel='linear', C=C)

In [71]:
multi_target_svm = MultiOutputClassifier(model_svc)  

# Fit the classifier to the data
multi_target_svm.fit(X_train, y_train)

# Predictions
y_pred = multi_target_svm.predict(X_test)
from sklearn.metrics import accuracy_score, multilabel_confusion_matrix,classification_report
print(accuracy_score(y_test, y_pred))
print(multilabel_confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.8557213930348259
[[[193   0]
  [  8   0]]

 [[176   4]
  [ 20   1]]

 [[192   0]
  [  9   0]]

 [[182   4]
  [ 14   1]]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.20      0.05      0.08        21
           2       0.00      0.00      0.00         9
           3       0.20      0.07      0.10        15

   micro avg       0.20      0.04      0.06        53
   macro avg       0.10      0.03      0.04        53
weighted avg       0.14      0.04      0.06        53
 samples avg       0.00      0.00      0.00        53



#### Evaluate the models
Perform a comparison between the predictive models. <br>
Report the accuracy, recall, precision and F1-score measures as well as the confusion matrix if it is a classification problem. <br>
Report the R2 score, mean squared error and mean absolute error if it is a regression problem.
______________________________________________________________________________________
Description: